id: IC7C95879
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-03-29T04:36:31+00:00'
last_modified: '2022-06-16T08:03:23.290901+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS23418
  title: དགེ་ལྡན་པའི་ལམ་རིམ་དང་སྙན་བརྒྱུད་ཀྱི་ཆོས་སྐོར།
  author: ''
  base:
    918B:
      image_group_id: I8LS23420
      title: ''
      total_pages: ''
      order: 1
      base_file: 918B.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
