id: IC7C95879
legacy_id: PBB16FEBB
ocr_import_info:
  bdrc_scan_id: W8LS23418
  source: bdrc
  ocr_info:
    timestamp: '2022-03-29T04:09:50'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-04T05:04:20.234744+00:00'
last_modified: 2022-09-04 13:05:10.479862
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W8LS23418
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW8LS23418
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དགེ་ལྡན་པའི་ལམ་རིམ་དང་སྙན་བརྒྱུད་ཀྱི་ཆོས་སྐོར།
  author: ཚེ་མཆོག་གླིང་ཡོངས་འཛིན་ཡེ་ཤེས་རྒྱལ་མཚན།
statistics:
  ocr_word_mean_confidence_index: 0.9446282458892405
  ocr_word_median_confidence_index: 0.99
quality: null
bases:
  I8LS23420:
    source_metadata:
      id: http://purl.bdrc.io/resource/I8LS23420
      total_pages: 698
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I8LS23420.txt
    statistics:
      ocr_word_median_confidence_index: 0.99
      ocr_word_mean_confidence_index: 0.9446282458892405
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
